In [1]:
WORK_DIR_PATH = ".."

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.chdir(WORK_DIR_PATH)
print(f"DIRECTORY: {os.getcwd()}")

DIRECTORY: c:\Users\jayar\Desktop\바탕 화면\REPO\PAPER REVIEW\RECSYS\02_MLP\04_RS-J-NCF

In [4]:
import sys
sys.path.append("src")

# Config

In [5]:
import pandas as pd
from recsys import config, utils

In [6]:
schema = config.builder.schema_builder()

# Movie Lens

In [7]:
# Upload Data
PATH = "./data/origin/movielens.csv"
origin = pd.read_csv(PATH)

In [8]:
origin

        userId  movieId  rating   timestamp
0            1        0     4.0   964982703
1            1        2     4.0   964981247
2            1        5     4.0   964982224
3            1       43     5.0   964983815
4            1       46     5.0   964982931
...        ...      ...     ...         ...
100831     610     9416     4.0  1493848402
100832     610     9443     5.0  1493850091
100833     610     9444     5.0  1494273047
100834     610     9445     5.0  1493846352
100835     610     9485     3.0  1493846415

[100836 rows x 4 columns]

In [9]:
# Positive feedback is limited to ratings of 3 or higher
pos_feedback = origin[origin["rating"]>=3]

In [10]:
# Columns
kwargs = dict(
    df=pos_feedback,
    schema=schema,
    col_user='userId', 
    col_item='movieId', 
)

data = utils.preprocessor.main(**kwargs)

In [11]:
data

        userId  itemId
0            2       2
1            2       4
2            2       7
3            2      45
4            2      48
...        ...     ...
100831     610    8202
100832     610    8225
100833     610    8226
100834     610    8227
100835     610    8256

[81763 rows x 2 columns]

In [12]:
# data Description
kwargs = dict(
    df=data,
    schema=schema,
    percentaile=0.9,
)

utils.description.main(**kwargs)

number of user: 609
number of item: 8452
total interaction: 81763
interaction density: 1.5885 %
max interaction of user: 2117
max interaction of item: 315
top 10.0 % interaction of user: 344.4
top 10.0 % interaction of item: 25.0
mean interaction of user: 134
mean interaction of item: 9

In [13]:
kwargs = dict(
    path_or_buf="./data/movielens.csv",
    index=False, 
    header=True,
)

data.to_csv(**kwargs)